### ISSUE TITLE
Silencing "Warning: no keys found for identity $USER in" when using ssh-agent and no key files

### ISSUE THREAD

**Issue by exponentactivity** [dyuri/repassh#4]
I am running repassh in Xonsh via xontrib-ssh-agent to connect to my ssh agent.

Every time i run `reepash`, `git` or `ssh`, i get this warning:

``` xonsh
@ repassh

Warning: no keys found for identity $USER in:
['/var/home/$USER/.ssh/identities/$USER', '/var/home/$USER/.ssh']
```

But this is to be expected, as i don't have any key files. Therefore i would like to silence this warning.

I am currently working around this by creating an unused keyfile.

Am i missing something? I looked in the README and tried reading the function that prints the warning, but i couldn't find a solution.

**Comment by dyuri** [comment]
Sorry, I missed this issue, I might add a `$REPASSH_SUPPRESS_NO_KEY_WARNING` environment variable, if it's set we don't show the warning.

**Comment by dyuri** [comment]
Oh, no need for that, that message is logged with `LOG_WARN` verbosity, so if you set `VERBOSITY` to `LOG_ERROR` (= `1`) in you config (which is usually `~/.config/repassh/config.json`), then you shouldn't see it anymore.

**Comment by dyuri** [comment]
Something like:
```
{
  "VERBOSITY": 1
}
```
should do.

**Comment by exponentactivity** [comment]
Thank you! That is perfect.
